"""Deterministic helper: derives a monthly A$1=SGD mean and the S$-to-A$ conversion
factor (1/mean) from the pinned RBA F11.1 snapshot, per CLAUDE.md §11 data decision 6
and docs/specs/SKILL-001_test_specification.md §0. Writes
skills/tne_exco/reference/monthly_aud_sgd_rate.csv and
skills/tne_exco/reference/rba_fx_provenance.yaml. Re-run only if the pinned snapshot
is deliberately replaced -- SOURCE_SHA256 below must then be updated to match, and
the change is a Skill content-hash change like any other.

Usage: python skills/tne_exco/reference/build_monthly_rates.py
"""

from __future__ import annotations

import csv
import hashlib
from collections import defaultdict
from datetime import datetime
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_REPO_ROOT = _HERE.parent.parent.parent
SOURCE_PATH = _REPO_ROOT / "synthetic_data" / "reference" / "RBA_F11.1_exchange_rates_published_2026-09-22.csv"
SOURCE_SHA256 = "ab6fa92d2301f6e6ad760284fb0abe00c188f5c688043ef2f4bdce8b4ec9cec7"

OUT_CSV = _HERE / "monthly_aud_sgd_rate.csv"
OUT_PROVENANCE = _HERE / "rba_fx_provenance.yaml"

_DATA_START_LINE = 11  # 0-based: lines 0-10 are the RBA file's metadata header block
_SGD_COLUMN_INDEX = 8  # 0-based, within a data row: date is index-less (the row's own first field)


def sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def build() -> None:
    actual_sha = sha256_file(SOURCE_PATH)
    if actual_sha != SOURCE_SHA256:
        raise SystemExit(
            f"source file changed: expected sha256 {SOURCE_SHA256}, got {actual_sha}. "
            "This script pins a specific RBA snapshot -- update SOURCE_SHA256 deliberately "
            "if the snapshot is meant to change, do not silently rebuild against a new one."
        )

    with SOURCE_PATH.open(encoding="utf-8-sig", newline="") as f:
        lines = f.readlines()

    monthly_values: dict[str, list[float]] = defaultdict(list)
    for line in lines[_DATA_START_LINE:]:
        line = line.strip()
        if not line:
            continue
        fields = next(csv.reader([line]))
        date_str = fields[0]
        try:
            date = datetime.strptime(date_str, "%d-%b-%Y")
        except ValueError:
            continue
        raw = fields[_SGD_COLUMN_INDEX].strip()
        if not raw:
            continue
        month_key = date.strftime("%Y-%m")
        monthly_values[month_key].append(float(raw))

    rows = []
    for month in sorted(monthly_values):
        values = monthly_values[month]
        mean = sum(values) / len(values)
        factor = 1.0 / mean
        rows.append((month, len(values), round(mean, 6), round(factor, 8)))

    with OUT_CSV.open("w", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["month", "sample_days", "aud_sgd_mean", "aud_per_sgd_factor"])
        writer.writerows(rows)

    OUT_PROVENANCE.write_text(
        "# Provenance for monthly_aud_sgd_rate.csv -- generated by build_monthly_rates.py.\n"
        "# aud_per_sgd_factor = 1 / (monthly mean of A$1=SGD), CLAUDE.md \xa711 data decision 6.\n"
        f"source_file: {SOURCE_PATH.name}\n"
        f"source_sha256: {SOURCE_SHA256}\n"
        f"generated_at: {datetime.utcnow().isoformat()}Z\n"
        f"months: {len(rows)}\n"
    )
    print(f"wrote {OUT_CSV} ({len(rows)} months) and {OUT_PROVENANCE}")


if __name__ == "__main__":
    build()
